namespace: testenv-apps
resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: node-image-placeholder
  newName: mikogs/project-template-node
  newTag: v0.1.6
