apiVersion: v1
kind: Service
metadata:
  name: node-region2
  labels:
    app: node-region2
spec:
  selector:
    app: node-region2
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30221
  type: NodePort
