apiVersion: v1
kind: Service
metadata:
  name: node-region3
  labels:
    app: node-region3
spec:
  selector:
    app: node-region3
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30131
  type: NodePort
